### ISSUE TITLE
Breaks With new MongoDB Driver v2.0

### ISSUE THREAD

**Issue by anktsrkr** [FoC-/MongoMembership#8]
After upgrading the MongoDB Driver in our website, this library broke, because from v2.0 onwards every thing is changed.

**Comment by FoC-** [comment]
That is great news. I will fix it, may be on next week.

**Comment by anktsrkr** [comment]
Hey,
I already upgraded this library which is compatible with v2.0.1. so if you want I can contribute too. :)

**Comment by FoC-** [comment]
Sounds great. Just do it. I will merge and deploy new nuget

**Comment by hkato** [comment]
Do you have a plan to release new nuget package?

**Comment by anktsrkr** [comment]
@hkato You can get the latest version [Here](https://github.com/anktsrkr/MongoMembership)

**Comment by hkato** [comment]
Yes I know the latest version. I want to use new mongomembership.x.y.z.nupkg binary from nuget.org.

**Comment by FoC-** [comment]
Sorry for a huge delay. I have uploaded the new version to nuget.

**Comment by hkato** [comment]
Thank you for the releasing nuget package, but it doesn't work in my environment.
I will report as new issues.

**Comment by hkato** [comment]
Please refer to #9 #10 #11

**Comment by hkato** [comment]
Thank you for the PR #10 #12 #13 . Could you release nuget binary?
If so please bump up the version number 1.0.1.0, 1.1.0.0 or something like that. also the version is in appleyor.yml. Current assembly version of nuget binary(1.0.0)  is not updated(0.1.0).

```diff
-version: 1.0.{build}
+version: 1.1.0.{build}
```

**Comment by FoC-** [comment]
Yes it is published now on [nuget.org](https://www.nuget.org/packages/MongoMembership/1.1.0) with new version.
